## makeCacheMatrix creates a matrix, 
## and caches it and its inverse.

## The method cacheSolve calculates the inverse of the matrix created by makeCacheMatrix  
## method if it is not already available in the cache.Else returns the inverse from cache.

##Takes a matrix as the input and returns the list of methods 
##to get and set the matrix and the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
	  m<-solve(x)
 	  set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) m <<- inverse
        getinverse <- function() m
        list(set = set, get = get,
             setinverse = setinverse ,
             getinverse = getinverse)

}


## Takes as input the list generated by makeCacheMatrix and returns the inverse of the matrix created from the cache.
##If the inverse is not in cache it is calculated. 

cacheSolve <- function(x, ...) {
          m <- x$getinverse()
          if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
	  
        data <- x$get()
        m <- solve(data)
        x$setinverse(m)
        m
}
